server:
    port: 8082
    context-path: /
#    tomcat:
#        uri-encoding: UTF-8
logging:
    level:
        tk.mybatis: DEBUG

spring:
    datasource:
#        url: jdbc:sqlserver://192.168.16.200:1433;DatabaseName=test
#        username: sa
#        password: 123456
#        # 使用druid数据源
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        name: test
        url: jdbc:mysql://127.0.0.1:3306/test
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request
    redis:
        master:
            host: 127.0.0.1
        slave:
            host: 127.0.0.1
#		password: 
        port: 6379
#		pool:
#			max-idle=8 # pool settings ...
#			min-idle=0
#			max-active=8
#			max-wait=-1
# redis config
#spring.redis.master.host=127.0.0.1
#spring.redis.master.port=6380

#spring.redis.slave.host=127.0.0.1
#spring.redis.slave.port=6381
dubbo:
    ref:
        url: dubbo://127.0.0.1:20880